apiVersion: v1
kind: Service
metadata:
  name: {{ include "sso-rag.fullname" . }}-api
  labels:
    {{- include "sso-rag.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    {{- include "sso-rag.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
