image:
  repository: ghcr.io/bcgov/sso-rag
  tag: v1.0.0-beta7
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 11434

resources:
  requests:
    cpu: "2"
    memory: "8Gi"
  limits:
    cpu: "4"

podAnnotations: {}
